### ISSUE TITLE
Scaling missaligns Overlay

### ISSUE THREAD

**Issue by jlnrrg** [Codelessly/ResponsiveFramework#80] opened 2021-12-03 12:31 UTC
As found out [here](https://github.com/talamaska/onboarding_overlay/issues/24), using a scaleFactor other than 1 leads to a missaligned Overlay.

This would in turn affect every package using such Overlay, and even custom `showMenu` methods.

scaleFactor 1.2            |  scaleFactor 1
:-------------------------:|:-------------------------:
![Screenshot from 2021-12-03 13-22-48](https://user-images.githubusercontent.com/77293597/144602871-28f4b3fc-b258-4a50-a481-7cf5c3f38aab.png)  |  ![Screenshot from 2021-12-03 13-27-25](https://user-images.githubusercontent.com/77293597/144602888-c492a3fa-3b04-406a-a3df-f5548d4a8525.png)

**Comment by jhuckabee** [comment] 2022-02-20 13:26
This looks like a duplicate of #67 and #75

**Comment by talamaska** [comment] 2022-04-07 11:04
FYI the reposition and wrong size is fixed in the onboarding_overlay with [3.1.0-pre.2](https://pub.dev/packages/onboarding_overlay/versions/3.1.0-pre.2)

**Comment by searchy2** [comment] 2022-07-05 04:31
Thank you @talamaska, closing issue as solved for now and moving conversation to this solution thread:
https://github.com/talamaska/onboarding_overlay/issues/33

**Closed by searchy2** 2022-07-05 04:31 UTC
