### ISSUE TITLE
Error when using this with flutter_staggered_grid_view

### ISSUE THREAD

**Issue by jasonlaw** [Codelessly/ResponsiveFramework#8] opened 2020-04-24 00:26 UTC
Hi,

I hit the following error when using this with flutter_staggered_grid_view which had been working fine before.

Do you this could be some bug in this framework, or the other package need to adjust to use this framework?

`Restarted application in 1,799ms.
I/flutter (32102): Start App.prerequisite()
I/flutter (32102): AppPrefs.init() ...
I/flutter (32102): AppConfig().init() ...
I/flutter (32102): AppApi.init()...
I/flutter (32102): AppLocalizations.init() ...
I/flutter (32102): AppSecurity.Init() ...
I/flutter (32102): App extensions...
I/flutter (32102): End App.prerequisite()

[38;5;248m════════ Exception caught by rendering library ═════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown during performLayout():[39;49m
'package:flutter_staggered_grid_view/src/rendering/sliver_staggered_grid.dart': Failed assertion: line 28 pos 16: 'cellExtent != null && cellExtent >= 0': is not true.

[38;5;248mEither the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
[39;49m

[38;5;244mThe relevant error-causing widget was[39;49m
    [38;5;248mDashboard[39;49m
[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;248m#2      new StaggeredGridConfiguration[39;49m
[38;5;248m#3      SliverStaggeredGridDelegateWithFixedCrossAxisCount.getConfiguration[39;49m
[38;5;248m#4      RenderSliverStaggeredGrid.performLayout[39;49m
[38;5;244m#5      RenderObject.layout[39;49m
[38;5;244m#6      RenderSliverEdgeInsetsPadding.performLayout[39;49m
[38;5;244m...[39;49m
[38;5;244mThe following RenderObject was being processed when the exception was fired: RenderSliverStaggeredGrid#e6f6e relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
[38;5;244mRenderObject: RenderSliverStaggeredGrid#e6f6e relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
    [38;5;244mneeds compositing[39;49m
    [38;5;244mparentData: paintOffset=Offset(8.0, 8.0) (can use size)[39;49m
    [38;5;244mconstraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 0.0, crossAxisExtent: 0.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 0.0, remainingCacheExtent: 242.0 cacheOrigin: 0.0 )[39;49m
    [38;5;244mgeometry: SliverGeometry(scrollExtent: 396.0, paintExtent: 396.0, maxPaintExtent: 396.0, cacheExtent: 396.0)[39;49m
        [38;5;244mscrollExtent: 396.0[39;49m
        [38;5;244mpaintExtent: 396.0[39;49m
        [38;5;244mmaxPaintExtent: 396.0[39;49m
        [38;5;244mcacheExtent: 396.0[39;49m
    [38;5;244mcurrently live children: 0,1,2,3,4,5,6[39;49m
    [38;5;244mchild with index 0: RenderIndexedSemantics#1feae NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
        [38;5;244mneeds compositing[39;49m
        [38;5;244mparentData: crossAxisOffset=0.0; index=0; layoutOffset=0.0[39;49m
        [38;5;244mconstraints: BoxConstraints(w=259.6, h=120.0)[39;49m
        [38;5;244msemantic boundary[39;49m
        [38;5;244msize: Size(259.6, 120.0)[39;49m
        [38;5;244mindex: 0[39;49m
        [38;5;244mchild: RenderRepaintBoundary#94153 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
            [38;5;244mneeds compositing[39;49m
            [38;5;244mparentData: <none> (can use size)[39;49m
            [38;5;244mconstraints: BoxConstraints(w=259.6, h=120.0)[39;49m
            [38;5;244mlayer: OffsetLayer#2b710[39;49m
                [38;5;244moffset: Offset(8.0, 8.0)[39;49m
            [38;5;244msize: Size(259.6, 120.0)[39;49m
            [38;5;244mmetrics: 0.0% useful (1 bad vs 0 good)[39;49m
            [38;5;244mdiagnosis: insufficient data to draw conclusion (less than five repaints)[39;49m
            [38;5;244mchild: RenderPhysicalShape#5f5dc NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                [38;5;244mneeds compositing[39;49m
                [38;5;244mparentData: <none> (can use size)[39;49m
                [38;5;244mconstraints: BoxConstraints(w=259.6, h=120.0)[39;49m
                [38;5;244mlayer: PhysicalModelLayer#efb07[39;49m
                    [38;5;244melevation: 14.0[39;49m
                    [38;5;244mcolor: Color(0xffffffff)[39;49m
                [38;5;244msize: Size(259.6, 120.0)[39;49m
                [38;5;244melevation: 14.0[39;49m
                [38;5;244mcolor: Color(0xffffffff)[39;49m
                [38;5;244mshadowColor: Color(0xffffffff)[39;49m
                [38;5;244mclipper: ShapeBorderClipper[39;49m
                [38;5;244mchild: RenderCustomPaint#51292 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                    [38;5;244mneeds compositing[39;49m
                    [38;5;244mparentData: <none> (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(w=259.6, h=120.0)[39;49m
                    [38;5;244msize: Size(259.6, 120.0)[39;49m
    [38;5;244mchild with index 1: RenderIndexedSemantics#a5792 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
        [38;5;244mneeds compositing[39;49m
        [38;5;244mparentData: crossAxisOffset=271.6190476190476; index=1; layoutOffset=0.0[39;49m
        [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
        [38;5;244msemantic boundary[39;49m
        [38;5;244msize: Size(123.8, 120.0)[39;49m
        [38;5;244mindex: 1[39;49m
        [38;5;244mchild: RenderRepaintBoundary#32d8b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
            [38;5;244mneeds compositing[39;49m
            [38;5;244mparentData: <none> (can use size)[39;49m
            [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
            [38;5;244mlayer: OffsetLayer#ce427[39;49m
                [38;5;244moffset: Offset(279.6, 8.0)[39;49m
            [38;5;244msize: Size(123.8, 120.0)[39;49m
            [38;5;244mmetrics: 0.0% useful (1 bad vs 0 good)[39;49m
            [38;5;244mdiagnosis: insufficient data to draw conclusion (less than five repaints)[39;49m
            [38;5;244mchild: RenderPhysicalShape#3ccc5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                [38;5;244mneeds compositing[39;49m
                [38;5;244mparentData: <none> (can use size)[39;49m
                [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
                [38;5;244mlayer: PhysicalModelLayer#09809[39;49m
                    [38;5;244melevation: 14.0[39;49m
                    [38;5;244mcolor: Color(0xffffffff)[39;49m
                [38;5;244msize: Size(123.8, 120.0)[39;49m
                [38;5;244melevation: 14.0[39;49m
                [38;5;244mcolor: Color(0xffffffff)[39;49m
                [38;5;244mshadowColor: Color(0xffffffff)[39;49m
                [38;5;244mclipper: ShapeBorderClipper[39;49m
                [38;5;244mchild: RenderCustomPaint#40635 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                    [38;5;244mneeds compositing[39;49m
                    [38;5;244mparentData: <none> (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
                    [38;5;244msize: Size(123.8, 120.0)[39;49m
    [38;5;244mchild with index 2: RenderIndexedSemantics#1c491 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
        [38;5;244mneeds compositing[39;49m
        [38;5;244mparentData: crossAxisOffset=0.0; index=2; layoutOffset=132.0[39;49m
        [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
        [38;5;244msemantic boundary[39;49m
        [38;5;244msize: Size(123.8, 120.0)[39;49m
        [38;5;244mindex: 2[39;49m
        [38;5;244mchild: RenderRepaintBoundary#423ae NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
            [38;5;244mneeds compositing[39;49m
            [38;5;244mparentData: <none> (can use size)[39;49m
            [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
            [38;5;244mlayer: OffsetLayer#f16a0[39;49m
                [38;5;244moffset: Offset(8.0, 140.0)[39;49m
            [38;5;244msize: Size(123.8, 120.0)[39;49m
            [38;5;244mmetrics: 0.0% useful (1 bad vs 0 good)[39;49m
            [38;5;244mdiagnosis: insufficient data to draw conclusion (less than five repaints)[39;49m
            [38;5;244mchild: RenderPhysicalShape#45911 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                [38;5;244mneeds compositing[39;49m
                [38;5;244mparentData: <none> (can use size)[39;49m
                [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
                [38;5;244mlayer: PhysicalModelLayer#9297f[39;49m
                    [38;5;244melevation: 14.0[39;49m
                    [38;5;244mcolor: Color(0xffffffff)[39;49m
                [38;5;244msize: Size(123.8, 120.0)[39;49m
                [38;5;244melevation: 14.0[39;49m
                [38;5;244mcolor: Color(0xffffffff)[39;49m
                [38;5;244mshadowColor: Color(0xffffffff)[39;49m
                [38;5;244mclipper: ShapeBorderClipper[39;49m
                [38;5;244mchild: RenderCustomPaint#cedea NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                    [38;5;244mneeds compositing[39;49m
                    [38;5;244mparentData: <none> (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
                    [38;5;244msize: Size(123.8, 120.0)[39;49m
    [38;5;244mchild with index 3: RenderIndexedSemantics#9183b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
        [38;5;244mneeds compositing[39;49m
        [38;5;244mparentData: crossAxisOffset=135.8095238095238; index=3; layoutOffset=132.0[39;49m
        [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
        [38;5;244msemantic boundary[39;49m
        [38;5;244msize: Size(123.8, 120.0)[39;49m
        [38;5;244mindex: 3[39;49m
        [38;5;244mchild: RenderRepaintBoundary#4601f NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
            [38;5;244mneeds compositing[39;49m
            [38;5;244mparentData: <none> (can use size)[39;49m
            [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
            [38;5;244mlayer: OffsetLayer#dc15d[39;49m
                [38;5;244moffset: Offset(143.8, 140.0)[39;49m
            [38;5;244msize: Size(123.8, 120.0)[39;49m
            [38;5;244mmetrics: 0.0% useful (1 bad vs 0 good)[39;49m
            [38;5;244mdiagnosis: insufficient data to draw conclusion (less than five repaints)[39;49m
            [38;5;244mchild: RenderPhysicalShape#927d4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                [38;5;244mneeds compositing[39;49m
                [38;5;244mparentData: <none> (can use size)[39;49m
                [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
                [38;5;244mlayer: PhysicalModelLayer#cc7c0[39;49m
                    [38;5;244melevation: 14.0[39;49m
                    [38;5;244mcolor: Color(0xffffffff)[39;49m
                [38;5;244msize: Size(123.8, 120.0)[39;49m
                [38;5;244melevation: 14.0[39;49m
                [38;5;244mcolor: Color(0xffffffff)[39;49m
                [38;5;244mshadowColor: Color(0xffffffff)[39;49m
                [38;5;244mclipper: ShapeBorderClipper[39;49m
                [38;5;244mchild: RenderCustomPaint#b812d NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                    [38;5;244mneeds compositing[39;49m
                    [38;5;244mparentData: <none> (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
                    [38;5;244msize: Size(123.8, 120.0)[39;49m
    [38;5;244mchild with index 4: RenderIndexedSemantics#6b451 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
        [38;5;244mneeds compositing[39;49m
        [38;5;244mparentData: crossAxisOffset=271.6190476190476; index=4; layoutOffset=132.0[39;49m
        [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
        [38;5;244msemantic boundary[39;49m
        [38;5;244msize: Size(123.8, 120.0)[39;49m
        [38;5;244mindex: 4[39;49m
        [38;5;244mchild: RenderRepaintBoundary#530c8 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
            [38;5;244mneeds compositing[39;49m
            [38;5;244mparentData: <none> (can use size)[39;49m
            [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
            [38;5;244mlayer: OffsetLayer#25faa[39;49m
                [38;5;244moffset: Offset(279.6, 140.0)[39;49m
            [38;5;244msize: Size(123.8, 120.0)[39;49m
            [38;5;244mmetrics: 0.0% useful (1 bad vs 0 good)[39;49m
            [38;5;244mdiagnosis: insufficient data to draw conclusion (less than five repaints)[39;49m
            [38;5;244mchild: RenderPhysicalShape#09280 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                [38;5;244mneeds compositing[39;49m
                [38;5;244mparentData: <none> (can use size)[39;49m
                [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
                [38;5;244mlayer: PhysicalModelLayer#6f653[39;49m
                    [38;5;244melevation: 14.0[39;49m
                    [38;5;244mcolor: Color(0xffffffff)[39;49m
                [38;5;244msize: Size(123.8, 120.0)[39;49m
                [38;5;244melevation: 14.0[39;49m
                [38;5;244mcolor: Color(0xffffffff)[39;49m
                [38;5;244mshadowColor: Color(0xffffffff)[39;49m
                [38;5;244mclipper: ShapeBorderClipper[39;49m
                [38;5;244mchild: RenderCustomPaint#5c0dd NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                    [38;5;244mneeds compositing[39;49m
                    [38;5;244mparentData: <none> (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
                    [38;5;244msize: Size(123.8, 120.0)[39;49m
    [38;5;244mchild with index 5: RenderIndexedSemantics#a426e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
        [38;5;244mneeds compositing[39;49m
        [38;5;244mparentData: crossAxisOffset=0.0; index=5; layoutOffset=264.0[39;49m
        [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
        [38;5;244msemantic boundary[39;49m
        [38;5;244msize: Size(123.8, 120.0)[39;49m
        [38;5;244mindex: 5[39;49m
        [38;5;244mchild: RenderRepaintBoundary#b4be8 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
            [38;5;244mneeds compositing[39;49m
            [38;5;244mparentData: <none> (can use size)[39;49m
            [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
            [38;5;244mlayer: OffsetLayer#79b49[39;49m
                [38;5;244moffset: Offset(8.0, 272.0)[39;49m
            [38;5;244msize: Size(123.8, 120.0)[39;49m
            [38;5;244mmetrics: 0.0% useful (1 bad vs 0 good)[39;49m
            [38;5;244mdiagnosis: insufficient data to draw conclusion (less than five repaints)[39;49m
            [38;5;244mchild: RenderPhysicalShape#97367 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                [38;5;244mneeds compositing[39;49m
                [38;5;244mparentData: <none> (can use size)[39;49m
                [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
                [38;5;244mlayer: PhysicalModelLayer#550df[39;49m
                    [38;5;244melevation: 14.0[39;49m
                    [38;5;244mcolor: Color(0xffffffff)[39;49m
                [38;5;244msize: Size(123.8, 120.0)[39;49m
                [38;5;244melevation: 14.0[39;49m
                [38;5;244mcolor: Color(0xffffffff)[39;49m
                [38;5;244mshadowColor: Color(0xffffffff)[39;49m
                [38;5;244mclipper: ShapeBorderClipper[39;49m
                [38;5;244mchild: RenderCustomPaint#d6907 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                    [38;5;244mneeds compositing[39;49m
                    [38;5;244mparentData: <none> (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
                    [38;5;244msize: Size(123.8, 120.0)[39;49m
    [38;5;244mchild with index 6: RenderIndexedSemantics#fc32b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
        [38;5;244mneeds compositing[39;49m
        [38;5;244mparentData: crossAxisOffset=135.8095238095238; index=6; layoutOffset=264.0[39;49m
        [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
        [38;5;244msemantic boundary[39;49m
        [38;5;244msize: Size(123.8, 120.0)[39;49m
        [38;5;244mindex: 6[39;49m
        [38;5;244mchild: RenderRepaintBoundary#56d10 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
            [38;5;244mneeds compositing[39;49m
            [38;5;244mparentData: <none> (can use size)[39;49m
            [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
            [38;5;244mlayer: OffsetLayer#dadac[39;49m
                [38;5;244moffset: Offset(143.8, 272.0)[39;49m
            [38;5;244msize: Size(123.8, 120.0)[39;49m
            [38;5;244mmetrics: 0.0% useful (1 bad vs 0 good)[39;49m
            [38;5;244mdiagnosis: insufficient data to draw conclusion (less than five repaints)[39;49m
            [38;5;244mchild: RenderPhysicalShape#6843b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                [38;5;244mneeds compositing[39;49m
                [38;5;244mparentData: <none> (can use size)[39;49m
                [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
                [38;5;244mlayer: PhysicalModelLayer#8ae6b[39;49m
                    [38;5;244melevation: 14.0[39;49m
                    [38;5;244mcolor: Color(0xffffffff)[39;49m
                [38;5;244msize: Size(123.8, 120.0)[39;49m
                [38;5;244melevation: 14.0[39;49m
                [38;5;244mcolor: Color(0xffffffff)[39;49m
                [38;5;244mshadowColor: Color(0xffffffff)[39;49m
                [38;5;244mclipper: ShapeBorderClipper[39;49m
                [38;5;244mchild: RenderCustomPaint#48e67 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                    [38;5;244mneeds compositing[39;49m
                    [38;5;244mparentData: <none> (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(w=123.8, h=120.0)[39;49m
                    [38;5;244msize: Size(123.8, 120.0)[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Reloaded 27 of 896 libraries in 1,078ms.
`

**Comment by jasonlaw** [comment] 2020-04-24 01:15
I have created a small project to reproduce the error, appreciate if you could take a look into this.

[test_with_flutter_staggered_grid_view.zip](https://github.com/Codelessly/ResponsiveFramework/files/4526101/test_with_flutter_staggered_grid_view.zip)

**Comment by searchy2** [comment] 2020-04-24 02:06
Thanks for using the Responsive Framework @jasonlaw 

I think I know what the issues is and it's already fixed in the next release. Let me test using your sample project.

**Comment by jasonlaw** [comment] 2020-04-24 07:13
Glad to hear that, thank you very much for this cool framework!

**Comment by searchy2** [comment] 2020-04-25 02:44
I've confirmed the issue is fixed. You can expect an update tomorrow.

**240px**
![MaxthonSnap20200424214228](https://user-images.githubusercontent.com/19896174/80269357-b3daa300-8674-11ea-8ff2-29596a211be1.png)
**4K**
![MaxthonSnap20200424214252](https://user-images.githubusercontent.com/19896174/80269366-b63cfd00-8674-11ea-84dd-2947d7a9c124.png)

Good to see the Responsive Framework working as intended :)

**Comment by jasonlaw** [comment] 2020-04-25 05:11
Excellent! Many thanks!

**Comment by searchy2** [comment] 2020-04-26 04:20
Responsive Framework v0.0.5 is now released :balloon:

**Closed** 2020-04-26 04:20 UTC
