### ISSUE TITLE
Text Fields hidden behind the Keyboard

### ISSUE THREAD

**Issue by rsbthebest** [Codelessly/ResponsiveFramework#16] opened 2020-07-17 07:07 UTC
Hi,

Let me start by saying this is an awesome plugin which am now using for all of my future projects! Amazing work there!

Now going back to the issue, I am working on an app which has a lot of text fields. I have notices that then the keypad opens about the amount of screen resizing (by Scaffold) which happens with the plugin is way less than what it does without the plugin. This is causing issue for me as the TextFields which is at the bottom of the screen is being covered by the keypad and there is no way to see what are we typing.

Here is my responsive configuration:

`MaterialApp(
      builder: (context, widget) => ResponsiveWrapper.builder(
        BouncingScrollWrapper.builder(context, widget),
          maxWidth: 2200,
          minWidth: 480,
          defaultScale: true,
          breakpoints: [
            ResponsiveBreakpoint.resize(480, name: MOBILE),
            ResponsiveBreakpoint.resize(800, name: TABLET),
            ResponsiveBreakpoint.autoScale(1000, name: DESKTOP),
          ],
      ),`

Here are the images for reference:

![Screenshot_20200717_123450](https://user-images.githubusercontent.com/12830614/87758494-2c8f6c80-c82a-11ea-8c6b-ef81f3412e00.jpg)
![Screenshot_20200717_123457](https://user-images.githubusercontent.com/12830614/87758499-2f8a5d00-c82a-11ea-89b7-a522a88f8a12.jpg)

Please have a look and let me know how this can be fixed!

Regards,
Rajdeep Barad

**Comment by searchy2** [comment] 2020-07-17 16:18
Thank you for the kind words and reporting this issue. I'll have a look this weekend!

**Comment by visual-velocity** [comment] 2020-07-26 06:32
Hey @searchy2 ,Fantastic work by you on your library but I'm also facing this issue on my production app. Please resolve it

**Comment by visual-velocity** [comment] 2020-07-26 06:34
Without implement library it's working fine but when we use library then we are facing issue

**Comment by visual-velocity** [comment] 2020-07-26 16:50
Hey @searchy2 Please resolve this issue , otherwise we will face very big problem in our app.

**Comment by searchy2** [comment] 2020-07-26 22:25
Feel free to give the problem a tackle and submit a PR with a fix. The library is open source so people can contribute!

**Comment by visual-velocity** [comment] 2020-08-05 12:15
We are try to solve this issue by many ways but we failed. Hey @searchy2 can you please cross-check this issue, actually we are facing this issue on our production app therefore we need resolution.

**Comment by danagbemava** [comment] 2020-08-06 22:06
@searchy2 I run a simulation and it seems that the issue with textview hidden behind the keyboard has to do with the defaultScale value. When it it set to false, the textfield isn't hidden behind the keyboard. It is when it is set to true. 
Configuration 1 for the ResponsiveWrapper 
`class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      builder: (ctx, widget) => ResponsiveWrapper.builder(
        widget,
        // maxWidth: 1200,
        // minWidth: 480,
        defaultScale: false,
        breakpoints: [
          ResponsiveBreakpoint.resize(480, name: MOBILE),
          ResponsiveBreakpoint.autoScale(800, name: TABLET),
          ResponsiveBreakpoint.resize(1000, name: DESKTOP),
        ],
      ),
      home: HomeScreen(),
    );
  }
}
`

result 
![Screenshot_1596751374](https://user-images.githubusercontent.com/52815643/89587281-de6df780-d830-11ea-9ed7-0f90830b312b.png)


Configuration 2 for the ResponsiveWrapper 
`class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      builder: (ctx, widget) => ResponsiveWrapper.builder(
        widget,
        // maxWidth: 1200,
        // minWidth: 480,
        defaultScale: true,
        breakpoints: [
          ResponsiveBreakpoint.resize(480, name: MOBILE),
          ResponsiveBreakpoint.autoScale(800, name: TABLET),
          ResponsiveBreakpoint.resize(1000, name: DESKTOP),
        ],
      ),
      home: HomeScreen(),
    );
  }
}`

result 
![Screenshot_1596751560](https://user-images.githubusercontent.com/52815643/89587374-08271e80-d831-11ea-84d3-829ba99e3f57.png)

**Comment by searchy2** [comment] 2020-08-06 22:08
Thanks for investigating and sharing your results. I'll take a look this weekend as I tackle the overlay issue.

**Comment by danagbemava** [comment] 2020-08-06 22:09
Sure, I'll be doing some more investigation to see if I can help come up with a fix for it

**Comment by visual-velocity** [comment] 2020-08-13 16:10
@danagbemava @searchy2 If we have set false to defaultScale then UI will not looking good.

**Comment by MaheshPeri19** [comment] 2020-08-14 02:45
Yes. I integrated textfield at bottom of the screen. When i set defaultScale: false, it is working fine, but getting ugly UI and RenderFlex overflowed errors. If defaultScale: true, UI is responsive, but textfied is hidden by keyboard.

**Comment by visual-velocity** [comment] 2020-08-14 03:29
Yes @MaheshPeri19 , you are right. THank u @danagbemava for your support and response. But due to this issue and not getting any helpful/responsive response from @searchy2 till now, so I'm removing this package from my organization's enterprise production app. We are wasting too much time to fix this this  issue from our end. Thank you and Sorry @searchy2

**Comment by danagbemava** [comment] 2020-08-14 09:18
> @danagbemava @searchy2 If we have set false to defaultScale then UI will not show good

I'm aware of this. I only pointed that out so that @searchy2 will have an idea of where to start when he's working on it

**Comment by lloretalvaro** [comment] 2020-08-16 22:56
I hope the keyboard problem can be solved soon! The package it's good but the keyboard problem it's a big issue

**Comment by visual-velocity** [comment] 2020-08-24 08:22
@searchy2 I hope you are working on this issue. The package is very good therefore we need it and We are also trying to resolve this issue.

**Comment by afnx** [comment] 2020-08-31 16:04
I was having the same problem. There is a workaround that I'm not sure yet. Wrap your TextField with the widget below:

```dart
import 'package:flutter/material.dart';
import 'package:responsive_framework/responsive_framework.dart';

class KeyboardAvoider extends StatelessWidget {
  final Widget child;

  KeyboardAvoider({this.child});

  @override
  Widget build(BuildContext context) {
    return AnimatedContainer(
      margin: EdgeInsets.only(
        bottom: MediaQuery.of(context).viewInsets.bottom > 0
            ? (ResponsiveWrapper.of(context).scaledHeight * MediaQuery.of(context).viewInsets.bottom) /
                ResponsiveWrapper.of(context).screenHeight
            : 0,
      ),
      duration: Duration(milliseconds: 300),
      child: child,
    );
  }
}
```

**Comment by lloretalvaro** [comment] 2020-08-31 16:30
@afnx I have tested your possible solution in several devices and at least for me it doesn't work, it's a shame that such a nice package have this type of error. 

I hope it can be solved soon! @searchy2

**Comment by afnx** [comment] 2020-08-31 19:29
@lloretalvaro Can you try this code in your MaterialApp?

```dart
class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomPadding: false,
      resizeToAvoidBottomInset: false,
      body: SingleChildScrollView(
        reverse: true,
        padding: EdgeInsets.all(20),
        child: KeyboardAvoider(
          child: SafeArea(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                Container(height: MediaQuery.of(context).size.height / 8),
                Text("TextField 1"),
                TextField(
                  decoration: InputDecoration(
                    hintText: "Type here",
                  ),
                ),
                Container(height: MediaQuery.of(context).size.height / 8),
                Text("TextField 2"),
                TextField(
                  decoration: InputDecoration(
                    hintText: "Type here",
                  ),
                ),
                Container(height: MediaQuery.of(context).size.height / 8),
                Text("TextField 3"),
                TextField(
                  decoration: InputDecoration(
                    hintText: "Type here",
                  ),
                ),
                Container(height: MediaQuery.of(context).size.height / 8),
                Text("TextField 4"),
                TextField(
                  decoration: InputDecoration(
                    hintText: "Type here",
                  ),
                ),
                Container(height: MediaQuery.of(context).size.height / 8),
                Text("TextField 5"),
                TextField(
                  decoration: InputDecoration(
                    hintText: "Type here",
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class KeyboardAvoider extends StatelessWidget {
  final Widget child;

  KeyboardAvoider({this.child});

  @override
  Widget build(BuildContext context) {
    return AnimatedContainer(
      margin: EdgeInsets.only(
        bottom: MediaQuery.of(context).viewInsets.bottom > 0
            ? (ResponsiveWrapper.of(context).scaledHeight * MediaQuery.of(context).viewInsets.bottom) /
                ResponsiveWrapper.of(context).screenHeight
            : 0,
      ),
      duration: Duration(milliseconds: 300),
      child: child,
    );
  }
```

**Comment by searchy2** [comment] 2020-09-01 03:49
Thanks for trying to create a fix. 

The problem is that certain Flutter widgets read layout metrics from an internal implementation of MediaQuery that accesses the root layout instead of the scaled layout.

I have no timeline for when this issue can be fixed.

**Comment by deep01code** [comment] 2020-09-04 17:07
@searchy2  PLEASE PLEASE PLEASE resolve this issue, I am in big trouble. When do you think this issue will be fixed.

Thanks in advance for your amazing work

**Comment by searchy2** [comment] 2020-09-04 17:15
I'll take a look today and this weekend.

**Comment by deep01code** [comment] 2020-09-04 17:19
@searchy2 I can't thank you enough, I really appreciate your help.

**Comment by visual-velocity** [comment] 2020-09-06 17:55
@searchy2 We are in big trouble.

**Comment by deep01code** [comment] 2020-09-09 20:20
@searchy2 :)

**Comment by deep01code** [comment] 2020-09-10 18:19
@searchy2 :)

**Comment by searchy2** [comment] 2020-09-10 19:42
@deep01code Please refrain from spamming this thread. I'm aware of the issue.

**Comment by deep01code** [comment] 2020-09-23 19:48
Dear @searchy2 

Please accept my apologies if I bothered you by asking again, but I am facing huge issues in my work. Is there any expected date for fixing this issue. 

Thanks in Advance.

**Comment by searchy2** [comment] 2020-10-24 05:16
Please test with the new v0.0.10 release.
The keyboard insets should be fixed.

**Comment by visual-velocity** [comment] 2020-10-24 07:10
> Please test with the new v0.0.10 release.
> The keyboard insets should be fixed.

Sure

**Comment by MaheshPeri19** [comment] 2020-11-08 01:06
Thank you very much. It is working perfectly now.

**Comment by searchy2** [comment] 2020-11-08 01:48
Amazing to hear. Can you confirm that TextFields show correctly for you @visual-velocity @deep01code?

**Comment by visual-velocity** [comment] 2020-11-08 06:56
Perfect , it's working now

**Comment by searchy2** [comment] 2020-11-08 16:34
Great to hear! All credit goes to @SpencerLindemuth

**Closed by searchy2** 2020-11-08 16:34 UTC

**Comment by visual-velocity** [comment] 2020-11-08 19:36
Than you for your hard work, you save lots of time..

**Comment by searchy2** [comment] 2020-11-08 20:50
Thank you for using the library! 
I'm doing the best I can to continuously improve and close out the issues 1 by 1. 
Any help is much appreciated.

**Comment by karimsayf** [comment] 2023-01-30 13:35
@searchy2  @SpencerLindemuth the issue is still facing me while I'm using that last version of your package ^0.2.0
