### ISSUE TITLE
Resize not working properly after 800 pixels of width in Flutter Web

### ISSUE THREAD

**Issue by franarolas** [Codelessly/ResponsiveFramework#21] opened 2020-09-09 16:56 UTC
So I've been testing a few things and it looks like the resize is not working properly when you have an screen width of more than 800 pixels.
As far as I know the following widgets are not working properly: TextField, TextFormField, RaisedButton.
I've shared a git project so you can see exactly what I mean:
[Git responsive test project](https://gitlab.com/juliansanchezpaez/responsive-test) (Test it in Flutter Web with different sizes)

When the screen width is smaller than 800 pixels, it resizes the widgets as usual, but when it is bigger, it just makes them wider.
With images it works perfectly.
If you need some more information just ask for it.
Thank you.

**Comment by searchy2** [comment] 2020-09-09 17:23
The ResponsiveFramework supports responsive behaviors, `autoScale`, `resize`, and `autoScaleDown`.
 
In the code below, you can see that a `resize` breakpoint is set at 800. 

```
ResponsiveBreakpoint.**autoScale**(425, name: MOBILE),
ResponsiveBreakpoint.**resize**(800, name: TABLET),
ResponsiveBreakpoint.resize(1000, name: DESKTOP),
```

Resize allows Flutter to resize the layout normally. Please play around with the responsive behaviors to understand how they affect resizing.

**Comment by franarolas** [comment] 2020-09-09 17:27
Even if I have it like that:```

ResponsiveBreakpoint.resize(425, name: MOBILE),
ResponsiveBreakpoint.resize(800, name: TABLET),
ResponsiveBreakpoint.resize(1000, name: DESKTOP),
```

It just resizes all widgets until 800, after it, it only resizes images, font sizes(and some more)

**Comment by gcostaapps** [comment] 2020-09-18 00:47
@franarolas I think you need to change the methods resize for autoscale to lock the UI and not make then wider.

**Comment by franarolas** [comment] 2020-09-24 16:10
> 
> 
> @franarolas I think you need to change the methods resize for autoscale to lock the UI and not make then wider.

It is the solution that I am using right now, but I don't think that is how it should work.

**Comment by searchy2** [comment] 2020-10-10 20:12
Resize is the default behavior which allows Flutter to layout normally.
If you want to increase the UI layout proportionally and `scale` the UI, use `AutoScale` instead.

Closing as working as intended. Please reopen if you have additional questions.

**Closed by searchy2** 2020-10-10 20:12 UTC
