### ISSUE TITLE
Error being thrown with the new version of the package 0.1.2

### ISSUE THREAD

**Issue by fdarsot** [Codelessly/ResponsiveFramework#55] opened 2021-06-25 04:25 UTC
hi @searchy2 

with the new version that supports landscape responsiveness, im getting an error thats being thrown by flutter itself.

i know its the plugin causing the error because when i comment out the code for responsive framework, the error goes away

the error is:
```

The following StateError was thrown during a scheduler callback:
Bad state: No element

When the exception was thrown, this was the stack:
#0      ListIterable.firstWhere (dart:_internal/iterable.dart:107:5)
#1      _ResponsiveWrapperState.getActiveBreakpointSegment
(package:responsive_framework/responsive_wrapper.dart:537:10)
#2      _ResponsiveWrapperState.getScreenWidth
(package:responsive_framework/responsive_wrapper.dart:233:31)
#3      _ResponsiveWrapperState.setDimensions
(package:responsive_framework/responsive_wrapper.dart:499:19)
#4      _ResponsiveWrapperState.initState.<anonymous closure>
(package:responsive_framework/responsive_wrapper.dart:581:7)
#5      SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1144:15)
#6      SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:1090:9)
#7      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure>
(package:flutter/src/scheduler/binding.dart:865:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and
dart:async-patch)

```

please check

**Comment by searchy2** [comment] 2021-06-25 04:27
Thank you for reporting the error. The is unfortunate and was likely introduced because of the landscape rewrite.

The stacktrace is helpful. Do you know how to reproduce the error?

**Comment by fdarsot** [comment] 2021-06-25 04:31
i do not know the specifics, but i expect it has something to do with the lists for each of the breakpoints "breakpointsLandscape and breakpoints"


if it helps my configuration is below:
```

child: MaterialApp(
        builder: (context, widget) => ResponsiveWrapper.builder(
          BouncingScrollWrapper.builder(context, widget),
          maxWidth: 1200,
          minWidth: 450,
          defaultScale: true,
          defaultScaleLandscape: true,
        
          breakpointsLandscape: [
            ResponsiveBreakpoint.autoScaleDown(
              450,
              name: MOBILE,
              scaleFactor: 0.73,
            ),
            ResponsiveBreakpoint.autoScaleDown(
              800,
              name: TABLET,
              scaleFactor: 0.73,
            ),
            ResponsiveBreakpoint.autoScaleDown(
              1000,
              name: TABLET,
              scaleFactor: 0.73,
            ),
            ResponsiveBreakpoint.autoScaleDown(
              1200,
              name: DESKTOP,
              scaleFactor: 0.73,
            ),
            ResponsiveBreakpoint.autoScaleDown(
              2460,
              name: "4K",
              scaleFactor: 0.73,
            ),
          ],
          breakpoints: [
            // mobile
            ResponsiveBreakpoint.resize(450, name: MOBILE),
         
            // tablet
            ResponsiveBreakpoint.resize(800, name: TABLET),
            
            // tablet
            ResponsiveBreakpoint.resize(1000, name: TABLET),
            
            // Desktop
            ResponsiveBreakpoint.resize(1200, name: DESKTOP),
         

            // 4K
            ResponsiveBreakpoint.resize(2460, name: "4K"),
          
          ],
        ),
        title: 'MyApp',
        theme: ThemeData(
          primarySwatch: Colors.red,
          fontFamily: 'WorkSans',
        ),
```

**Comment by fdarsot** [comment] 2021-06-26 05:49
@searchy2 any luck with a fix?

**Comment by searchy2** [comment] 2021-07-01 21:59
I'll take a look this weekend!

**Comment by searchy2** [comment] 2021-07-07 05:07
This error should have been caught by the tests. Unfortunately, the test being run didn't account for resetting the wrapper to test initialization.

The issue should now be fixed in v0.1.4

I apologize for the crashes.

**Comment by searchy2** [comment] 2021-07-07 05:07
#56 issue is also resolved!

**Comment by fdarsot** [comment] 2021-07-07 05:19
Thank you!!

**Comment by searchy2** [comment] 2021-07-12 22:24
Please reopen if you find the issue is still occuring.

**Closed by searchy2** 2021-07-12 22:24 UTC
